### ISSUE TITLE
CloudEvent.ExtensionAttributes collection is empty

### ISSUE THREAD

**Issue by richardterris** [cloudevents/sdk-csharp#319] opened 2024-12-17 15:35 UTC
I'm not sure if I'm doing something wrong, or if this is a bug. I have read through the documentation and while there is plenty of information about design decisions, there aren't a lot of specific instructions or examples.

I asked the question in the appropriate slack channel but was directed here.

I'm trying to include a custom attribute, 'datamechanism', in my event payload, at the parent level as a sibling of 'specversion' et al.

When I debug my application and inspect the CloudEvent object, the ExtensionAttributes collection is empty, and I can't find my attribute anywhere else in the deserialized object.

I have tried the following:

1. set 'datacontenttype' to application/cloudevents+json
2. set the Content-Type header to application/cloudevents+json
3. including the attribute as a header called ce-datamechanism
4. Following the dotnet core sample [here](https://github.com/cloudevents/sdk-csharp/blob/main/samples/CloudNative.CloudEvents.AspNetCoreSample/CloudEventJsonInputFormatter.cs) I have added this formatter, which I believe is responsible for deserializing the incoming payload to the CloudEvent object. From what I understood in the documentation, this shouldn't be necessary as I believe the standard CloudEventFormatter should handle extension attributes automatically, but please correct me if I'm wrong about this. It does seem to me that any non required or optional attributes perhaps should be automatically inserted into some array where they could be accessed. 
5. registered the formatter in Program.cs like so `builder.Services.AddControllers(opts =>
    opts.InputFormatters.Insert(0, new CloudEventJsonInputFormatter(new JsonEventFormatter())));` - this formatter isn't executing which tells me I am either failing to register it correctly, or that the Carter library isn't playing nicely with cloud events, perhaps it's doing some deserialization before my formatter can? [Carter](https://github.com/CarterCommunity/Carter)

I'm hoping someone can help me whether this is a bug or not.

Thanks!

**Comment by jskeet** [comment] 2024-12-17 15:44
If you could provide a minimal reproducible example, that would make it a lot easier for me to work out what's going on. I'm on vacation from the end of today, so I *may* not get to this before January, but I'll have a look if I can.

(If the repro could be a plain console app rather than requiring a web app, that would be really helpful too.)

**Comment by jskeet** [comment] 2024-12-17 16:30
> I'm not sure whether the Carter library is impacting it or not, but I don't think Carter will work in a Console application.

So that's why the first thing to do is to try to reproduce the problem *without* Carter. I've never used Carter, and don't really want to get to know a whole new library in order to reproduce a problem. If there's a bug in the library, it should be reproducible without Carter - and if there's a bug in Carter, I'm definitely not going to be a good person to find it.

**Comment by richardterris** [comment] 2024-12-17 18:33
Here is a repo containing a simplified version without Carter.
I've debugged and can confirm the same results - nothing in the ExtensionAttributes collection, and no sign of my attribute

https://github.com/richardterris/CloudEventTest/tree/main

**Comment by richardterris** [comment] 2024-12-17 18:33
`curl --location 'http://localhost:5124/game' \
--header 'Content-Type: application/cloudevents+json' \
--header 'ce-datamechanism: HELLO' \
--data '{
    "specversion": "1.0",
    "dataschema": "https://fakedataschema.com",
    "type": "com.fake",
    "source": "https://fakeyfakefake.com",
    "id": "9836f1ba-246e-4f7b-801d-26370d850bc0",
    "time": "2024-07-18T13:19:00Z",
    "datacontenttype": "application/cloudevents+json",
    "datamechanism": "PUSH",
    "data":
    {
       "gameId": "3728"
    }
}'`

Here is a curl command for the payload I'm sending

**Comment by jskeet** [comment] 2024-12-17 18:45
I don't see anything in your code to use the CloudEvents HTTP conversions etc. You can't just deserialize `CloudEvent` from JSON using System.Text.Json etc.

From https://github.com/cloudevents/sdk-csharp/blob/main/docs/guide.md:

> Sample code for consuming a CloudEvent within an ASP.NET Core `HttpRequest`:
>
> ```csharp
> CloudEventFormatter formatter = new JsonEventFormatter();
> CloudEvent cloudEvent = await request.ToCloudEventAsync(formatter);
```

So if you change your API lambda to accept an `HttpRequest`, you can do that.

**Comment by richardterris** [comment] 2024-12-17 19:14
That part of the documentation seemed a little unclear to me but I did try it before.

Doing that again now produces an error:

`Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.LoadAsync(JsonReader reader, JsonLoadSettings settings, CancellationToken cancellationToken)
   at CloudNative.CloudEvents.NewtonsoftJson.JsonEventFormatter.DecodeStructuredModeMessageAsync(Stream body, ContentType contentType, IEnumerable`1 extensionAttributes)
   at CloudNative.CloudEvents.AspNetCore.HttpRequestExtensions.ToCloudEventAsync(HttpRequest httpRequest, CloudEventFormatter formatter, IEnumerable`1 extensionAttributes)
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in /Users/rterris/Documents/Projects/CloudTest/Program.cs:line 16
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:5124
User-Agent: PostmanRuntime/7.42.0
Accept-Encoding: gzip, deflate, br
Content-Type: application/cloudevents+json
Content-Length: 362
ce-datamechanism: HELLO
Postman-Token: 9ee8fd62-ef3e-4498-9088-2697fe322501
`

**Comment by jskeet** [comment] 2024-12-17 19:19
Please update your repo so that I can reproduce it. It sounds like something's already read the request by that point.

**Comment by richardterris** [comment] 2024-12-17 19:26
Updated

**Comment by jskeet** [comment] 2024-12-17 19:37
Right, the problem is that you've still got a `CloudEvent` parameter, which ASP.NET Core is trying to populate with the request body - which means no longer available when you deserialize it in the method.

Just change the code to `app.MapPost("/game", async(HttpRequest request) => { ... }` and it works fine - including the `datamechanism` extension attribute.

(Note, however, that you shouldn't have the `ce-datamechanism` header there - that's mixing structured mode and binary mode. The body of your request contains the full CloudEvent, so that's using structured mode.)

**Comment by richardterris** [comment] 2024-12-17 19:42
Aha! Fantastic! 

So I was right to assume this was something I was doing wrong from the beginning! 
Thanks a lot for taking a look!

Is it possible to contribute to the samples codebase? If so I'd like to add this as an example to help others.

**Comment by jskeet** [comment] 2024-12-17 19:43
Yes, feel free to create a PR that adds a Minimal API example. I'll close this issue now.

**Closed by jskeet** 2024-12-17 19:43 UTC
