### ISSUE TITLE
[Question] How to get a Amqp.Message object from byte array using a AMQP broker

### ISSUE THREAD

**Issue by BOLT04** [cloudevents/sdk-csharp#184] opened 2021-08-19 16:06 UTC
Hello everyone 👋,

I'm having trouble decoding an AMQP message sent to a RabbitMQ broker. My use case is that I don't have access to the `Amqp.ByteBuffer` returned when we call `message.Encode()`. My question is how could we write this test, decoding the message without access to the byte buffer, or how can we create a ByteBuffer from a byte array?

https://github.com/cloudevents/sdk-csharp/blob/42b723d844506d27faff33cc477fc07f210c1430/test/CloudNative.CloudEvents.UnitTests/Amqp/AmqpTest.cs#L75-L77

Here is a snippet of the code I'm using to test the cloud events SDK, using these dependencies:

![imagem](https://user-images.githubusercontent.com/18630253/130101682-943dfdec-e853-463e-87da-f10cf2217db7.png)

```csharp
// Receive the message
var channel = con.CreateModel();
var consumer = new EventingBasicConsumer(channel);

// add the message receive event
consumer.Received += (model, deliveryEventArgs) => 
{
    byte[] body = deliveryEventArgs.Body.ToArray();
    ByteBuffer buffer = new ByteBuffer(body, 0, 0, body.Length);

    var decodedMessage = Amqp.Message.Decode(buffer);
    var receivedCloudEvent = decodedMessage.ToCloudEvent(new JsonEventFormatter());     

    channel.BasicAck(deliveryEventArgs.DeliveryTag, false);
};

return channel.BasicConsume(consumer, "demoqueue");
```

In the receiver code, I have access to the byte array of the message, so I try to create a new ByteBuffer to then call `Amqp.Message.Decode(buffer);`. This results in a `NullReferenceException` since all fields in the `Message` are `null`:

![imagem](https://user-images.githubusercontent.com/18630253/130102719-d56d496f-c317-486c-a868-713f11fe55ce.png)

Any help is much appreciated, thank you!

**Comment by jskeet** [comment] 2021-08-19 16:09
It sounds like your problem is before you get to the CloudEvents code... in which case I don't think this is really a CloudEvents SDK issue. Perhaps you'd be better off posting this in an AMQP-specific repo?

**Comment by BOLT04** [comment] 2021-08-19 21:49
Hi @jskeet, thank you for the response.
Yes, this might be an issue more related to **AMQPNetLite** when publishing the message to the broker. This is the code I'm using for publishing:

```csharp
var model = con.CreateModel();
var properties = model.CreateBasicProperties();
properties.Persistent = false;
 
CloudEvent cloudEvent = new CloudEvent
{
  Id = "event-id",
  Type = "event-type",
  Source = new Uri("https://cloudevents.io/"),
  Time = DateTimeOffset.UtcNow,
  DataContentType = "text/plain",
  Data = "This is CloudEvent data"
};
Amqp.Message message = cloudEvent.ToAmqpMessage(ContentMode.Structured, new JsonEventFormatter());
model.BasicPublish("demoExchange", "directexchange_key", properties, message.Encode().Buffer);
```

But if I try to decode these bytes in the receiving end with UTF-8 I get this string: `Ss?‼@@@@@@?
text/plainSt??
?↨cloudEvents:specversion?♥1.0?♫cloudEvents:idevent-id?►cloudEvents:type?
event-type?↕cloudEvents:source?↨https://cloudevents.io/?►cloudEvents:time?☺{^???Su?↨This is CloudEvent data`, which is in a weird format.

Do you know if I'm supposed to publish the message in a different way, or maybe I have to use some extension from `CloudNative.CloudEvents.Amqp`?

**Comment by jskeet** [comment] 2021-08-20 06:16
If you're trying to interpret the AMQP message *as if it were text* I'd expect that to fail.

I suggest you try taking CloudEvents out of the picture - try creating a message just populating a few properties (including with a byte array, e.g. just `{ 1, 2, 3, 4 }`) and make sure you can publish and receive that appropriately.

I'm going to close this as I don't think the problem is really anything to do with CloudEvents. If, after you've done more investigation into how to use AMQP appropriately, you can provide an example showing that the issue *is* in the CloudEvents SDK, I'll be happy to reopen the issue and work on it.

**Closed by jskeet** 2021-08-20 06:16 UTC
