### ISSUE TITLE
ContentType decode exception

### ISSUE THREAD

**Issue by Mewriick** [cloudevents/sdk-csharp#79] opened 2020-11-20 06:23 UTC
Hello,

I receive this expcetion while I try to deserialize event which I receive from Azure Service Bus.
Excaption:
```cs
The 'contenttype' attribute value must be a content-type expression compliant with RFC2046
   at CloudNative.CloudEvents.CloudEventAttributes.ValidateAndNormalize(String key, Object& value)
   at CloudNative.CloudEvents.CloudEventAttributes.set_Item(String key, Object value)
   at CloudNative.CloudEvents.JsonEventFormatter.DecodeJObject(JObject jObject, IEnumerable`1 extensions)
   at CloudNative.CloudEvents.JsonEventFormatter.DecodeStructuredEvent(Byte[] data, IEnumerable`1 extensions)
```

The event looks like this:

```json
{
  "DataContentType": {
    "Boundary": null,
    "CharSet": null,
    "MediaType": "application/json",
    "Name": null,
    "Parameters": []
  },
  "Data": {
    "OrderNumber": "#",
    "TrackingNumber": "#",
    "StateId": 5
  },
  "Id": "dbb05af1-d0fb-46ee-9c8e-df585c02362a",
  "DataSchema": null,
  "Source": "http://localhost:61974/",
  "SpecVersion": 3,
  "Subject": "510589659",
  "Time": "2020-11-20T05:26:56.8365438Z",
  "Type": "trackandtrace.order.statechanged"
}
```

Event creation looks like this:
```cs
var message = new CloudEvent(Types.OrderStateChanged, _configuration.BaseUri)
{
	Data = new TransportStateChanged
	{
		OrderNumber = orderInfo.OrderNumber,
		TrackingNumber = orderInfo.TrackingNumber,
		StateId = orderInfo.StateId
	},
	DataContentType = new ContentType("application/json"),
	Subject = orderInfo.OrderNumber
};
```

Event deserialization is done by `JsonEventFormatter` with `byte[]` parameter. 

Is there anything that I miss when I create or deserialize message?

I check `JsonEventFormatter` code and maybe this is the problem
```cs
switch (item.Value.Type)
{
	case JTokenType.String:
		attributes[item.Key] = item.Value.ToObject<string>();
		break;
	case JTokenType.Date:
		attributes[item.Key] = item.Value.ToObject<DateTime>();
		break;
	case JTokenType.Uri:
		attributes[item.Key] = item.Value.ToObject<Uri>();
		break;
	case JTokenType.Null:
		attributes[item.Key] = null;
		break;
	case JTokenType.Integer:
		attributes[item.Key] = item.Value.ToObject<int>();
		break;
	default:
		attributes[item.Key] = item.Value;
		break;
}
```

bacause in `CloudEventAttributes` is value type compared to `string` or `ContentType` but actual type is `Newtonsoft.Json.Linq.JObject`

**Comment by kulliapi** [comment] 2020-12-02 11:40
Hello i can confirm the Problem. The Exception wich is thrown is the following:
_**The 'contenttype' attribute value must be a content-type expression compliant with RFC2046**_
There are two Solutions in my Opinion. If the ContentType is  "application/json" it could be leave blank and will serialize. Mentioned in the **primer** that it is **optional** [here](https://github.com/cloudevents/spec/blob/v1.0/spec.md#context-attributes). The Other way would to add a custom JsonEventFormatter which will handle the mismatch of types.

Maybe the problem can be solved in the Git Project.

Best regards

**Comment by Hoaas** [comment] 2021-01-15 14:10
Seems this is a change in .NET5. This have broken a few APIs here after upgrading. 

Also reproduced here: dotnet/aspnetcore#29343

**Comment by jskeet** [comment] 2021-02-12 16:36
@Mewriick: I'd like to look into this in more detail - do you know what the HTTP request looks like? We've recently overhauled a lot of the foundations of the CloudEvents SDK, and I'd like to check whether either this is already fixed, or whether it can be easily.

**Comment by Mewriick** [comment] 2021-02-18 05:28
@jskeet I had this issue with deserializing message from Azure Servie Bus. Event which I send into event bus a attach in first comment. So I cannot say how the HTTP request looks like.

**Comment by jskeet** [comment] 2021-02-18 06:54
Okay, looking at this again, that event content is *definitely* incorrect, and the decoding side was correct to fail. In fact, it's not just the datacontenttype attribute that's a problem here - the casing of everything is broken. (All attributes should be lower case.)

It's still not clear to me what you do with the message after constructing it directly - my guess is that you're just using Json.NET or similar, which will *not* correctly serialize the CloudEvent.

If you could post more complete code for both ends, that would help - it's all changing quite a lot at the moment, but I suspect the fundamentals will stay the same.

**Comment by Mewriick** [comment] 2021-02-18 07:21
@jskeet 
Here is code how message is constructing
```cs
var message = new CloudEvent(Types.OrderStateChanged, _configuration.BaseUri)
{
	Data = new TransportStateChanged
	{
		OrderNumber = orderInfo.OrderNumber,
		TrackingNumber = orderInfo.TrackingNumber,
		StateId = orderInfo.StateId
	},
	Subject = orderInfo.OrderNumber,
	DataContentType = new ContentType("application/json")
};
```

Here is code which is responsible for sending message through bus. `JsonConvert` is from `Newtonsoft.Json`
```cs
var data = JsonConvert.SerializeObject(message);
var azureMessage = new Message(Encoding.UTF8.GetBytes(data));

try
{
	await _topicClient.SendAsync(azureMessage);
}
```

**Comment by jskeet** [comment] 2021-02-18 07:31
Right - that's not how you should serialize a `CloudEvent`.

In the currently-released code, you'd use `ICloudEventFormatter.EncodeStructuredEvent`; in #97 which I'll merge soon you'd use `CloudEventFormatter.EncodeStructuredModeMessage`. That's basically encoding the CloudEvent in a way that contains all the relevant information, just as you would using HTTP etc.

Then you use the equivalent decoding method on the other side.

**Comment by Mewriick** [comment] 2021-02-18 07:33
Thanks, I will try.

Also this is consumer part deserialization

```cs
var deserializedMessage = _jsonEventFormatter.DecodeStructuredEvent(message.Body);
var payload = JsonSerializer.Deserialize<TransportStateChanged>(deserializedMessage.Data.ToString());
```

Is this correct?

**Comment by jskeet** [comment] 2021-02-18 07:41
The payload part isn't necessarily correct, although it *might* be. I'm afraid I've been changing this part of the code quite a bit, and I can't remember what it *used* to do. Looking at the code, I *think* `Data` will end up being a `JObject` - meaning that this probably will work, but is inefficient. You might want to test for it being a `JObject` and call `ToObject<TransportStateChanged>` on it if so, to avoid it formatting the JSON then having to reparse it.

In the next release, all of this will be a lot clearer...

**Comment by jskeet** [comment] 2021-03-04 16:53
Hi @Mewriick - have you been able to try this at all? It would be good to close this issue if we believe it's no longer a problem.

**Comment by Hoaas** [comment] 2021-03-04 17:46
I have misunderstood the original issue here, but CloudEvent deserialization in a .NET5 API with 2.0.0-beta1 packages also fail on Content-Type deserialization.

``````

**Comment by jskeet** [comment] 2021-03-04 17:50
@Hoaas: Is that with a request with the content from the first comment? If so, I'll try it with the current code (which has changed quite a bit since 2.0.0-beta1).

**Comment by Hoaas** [comment] 2021-03-04 17:55
Yes, both that event and everything else I've tried. :/

**Comment by jskeet** [comment] 2021-03-04 17:58
Interesting - we do have an [integration test](https://github.com/cloudevents/sdk-csharp/blob/master/test/CloudNative.CloudEvents.IntegrationTests/AspNetCore/CloudEventControllerTests.cs) which passes, using the [ASP.NET Core sample project](https://github.com/cloudevents/sdk-csharp/tree/master/samples/CloudNative.CloudEvents.AspNetCoreSample). I note that the integration test's name is inappropriate though, so there may be all kinds of other things wrong.
I'll *try* to look at this soon.

**Comment by jskeet** [comment] 2021-03-05 08:28
I've managed to get it to work using curl, but:

- You need to specify the content-type header
- The body in the first comment is definitely not a valid CloudEvent

Here's a request body that worked for me:

```text
{
  "datacontenttype": "application/json",
  "data": {
    "OrderNumber": "#",
    "TrackingNumber": "#",
    "StateId": 5
  },
  "id": "dbb05af1-d0fb-46ee-9c8e-df585c02362a",
  "dataschema": null,
  "source": "http://localhost:61974/",
  "specversion": "1.0",
  "subject": "510589659",
  "time": "2020-11-20T05:26:56.8365438Z",
  "type": "trackandtrace.order.statechanged"
}
```

And the curl command line to send it to a controller listening on `/event`:

```text
curl -X POST -d @body.txt -H "Content-Type: application/cloudevents+json" http://localhost:5000/event
```

That's using the current "HEAD" code - I haven't tried that with the 2.0.0-beta1 release.

I'm minded to close this issue now as I believe all the issues were either in usage (serializing an event using Json.NET) or in earlier versions of the code. Any objections?

**Comment by Mewriick** [comment] 2021-03-05 08:55
Hello,

yes you can close this issue. When you plan release these changes as stable version?

Thanks a lot

**Comment by jskeet** [comment] 2021-03-05 09:02
> When you plan release these changes as stable version?

There's still quite a lot of work to do before we can release 2.0. (Just look at all the TODOs around, as well as the issues.)

Basically I see 2.0 as our final chance to get the public API "right" - there are few enough users of 1.0 that we're happy to take breaking changes to get to 2.0, but I'd expect 2.0 to get a lot more traction (due to CloudEvents themselves getting more traction) - so we need to be careful.

I'd like to hope that it'll be mid-Q2, but I'm not promising anything.

**Closed by jskeet** 2021-03-05 09:02 UTC
